CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP                               NOT NULL,
    updated_at TIMESTAMP                               NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE wishes
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(255)                            NOT NULL,
    description  VARCHAR(1000),
    completed    BOOLEAN                                 NOT NULL,
    priority     INT,
    category     VARCHAR(255),
    due_date     TIMESTAMP,
    completed_at TIMESTAMP,
    user_id      BIGINT                                  NOT NULL,
    created_at   TIMESTAMP                               NOT NULL,
    updated_at   TIMESTAMP                               NOT NULL,
    CONSTRAINT pk_wishes PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE wishes
    ADD CONSTRAINT FK_WISHES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);