services:
  app:
    build: .
    container_name: wishlist-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      JWT_SECRET: ${JWT_SECRET}
    env_file:
      - .env
    labels:
      - "swagger.docs.enabled=true"
      - "swagger.docs.path=/api/swagger-ui.html"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
