services:
  app:
    build: .
    container_name: wishlist-app
    ports:
      - "8080:8080"
      - "5005:5005"  # for debugging, don't use on PROD
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      JWT_SECRET: ${JWT_SECRET}
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
