services:
  postgres:
    image: postgres:15.4
    container_name: wishlist-postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: wishlistdb
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped

  redis:
    image: redis:7.4.2
    container_name: wishlist-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  pgdata:
