# Server Configuration
server:
  port: 8080
  servlet.context-path: /api

# H2 Database Configuration
spring:
  datasource:
    url: jdbc:h2:mem:wishlistdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    # Performance Tuning
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10

  # JPA Configuration
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.hibernate.format_sql: true

  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false

# JWT Configuration
jwt:
  secret: yourSecretKeyHereMakeItLongAndComplexToEnsureSecurityOfTheTokens
  expiration: 86400000

# Logging
logging.level:
  org.springframework.web: INFO
  org.hibernate: ERROR
  com.wishlist: DEBUG